### ISSUE TITLE
Janitorr template pointing to latest

### ISSUE THREAD

**Issue by Schaka** [JamsRepos/Unraid-Templates#1]
First off, you should've at least asked for permission before releasing Janitorr to Unraid.

Now I'm running the risk of incorrect bug reports from people who aren't aware of update notes or haven't seen potentially updated instructions because they're out of sync. There was a reason I put neither Janitorr not rarrnomore directly on Unraid. 

Point in case, your template points to the latest image. A couple weeks ago, I noticed that GitHub automatically adds the latest tag to whatever image is published most recently. I changed it to commits to master automatically get tagged stable. You may want to adjust that in your template.

Additionally, I'd highly recommend using the native images instead. Memory footprint is significantly lower and there's no JVM overhead. For a small app like Janitorr, the advantages outweigh the advantages of having JIT easily.

**Comment by JamsRepos** [comment]
Don't appreciate your patronising message. I don't need your permission to publish an app to a store. You can always submit an official app if you're worried about someone else doing it. If you made this post with a little more friendliness, I might listen.

You are given the ability to choose the native image when setting up the application, you'd see that if you checked the template. You would also see that the application also states it requires knowledge of a configuration file. I've checked your repository and there is no bug reports. You mention risk however there's a risk with all apps having bug reports. Don't theorise negatives caused by me helping.
